# Generated by Django 4.2.16 on 2024-11-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='name',
            new_name='bus_name',
        ),
        migrations.RenameField(
            model_name='bus',
            old_name='journey_duration',
            new_name='duration',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='boarding_point',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='dropping_point',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='seats_available',
        ),
        migrations.AddField(
            model_name='bus',
            name='available_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bus',
            name='arrival_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bus',
            name='departure_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bus',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
