# Generated by Django 4.2.16 on 2024-11-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_rename_name_bus_bus_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='arrival_location',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='bus',
            old_name='departure_location',
            new_name='source',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='bus_type',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='price',
        ),
        migrations.AddField(
            model_name='bus',
            name='total_seats',
            field=models.IntegerField(default=32),
        ),
        migrations.AlterField(
            model_name='bus',
            name='arrival_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='bus',
            name='departure_time',
            field=models.TimeField(),
        ),
    ]
