# Generated by Django 4.2.16 on 2024-11-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_rename_arrival_location_bus_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='arrival_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bus',
            name='departure_time',
            field=models.DateTimeField(),
        ),
    ]
