# Generated by Django 4.2.16 on 2024-11-28 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_remove_bookings_bus_remove_bookings_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=100)),
                ('to_location', models.CharField(max_length=100)),
                ('boarding_points', models.JSONField(default=list)),
                ('dropoff_points', models.JSONField(default=list)),
            ],
        ),
        migrations.RemoveField(
            model_name='buses',
            name='base_fare',
        ),
        migrations.RemoveField(
            model_name='buses',
            name='rating_count',
        ),
        migrations.AddField(
            model_name='buses',
            name='booked_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='buses',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='buses',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='buses',
            name='total_seats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='buses',
            name='type',
            field=models.CharField(choices=[('AC Sleeper', 'AC Sleeper'), ('Non AC Sleeper', 'Non AC Sleeper'), ('AC Seater', 'AC Seater'), ('Non AC Seater', 'Non AC Seater')], max_length=50),
        ),
        migrations.AddField(
            model_name='buses',
            name='route',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='reservation.route'),
            preserve_default=False,
        ),
    ]
