# Generated by Django 4.2.16 on 2024-11-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_route_remove_buses_base_fare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buses',
            name='base_fare',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
