# Generated by Django 4.2.16 on 2024-12-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0012_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='is_held',
            field=models.BooleanField(default=False),
        ),
    ]
