# Generated by Django 4.2.16 on 2024-12-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0016_passengerdetail_email_passengerdetail_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerdetail',
            name='status',
            field=models.CharField(choices=[('primary', 'Primary Passenger'), ('co_passenger', 'Co-Passenger')], default='co_passenger', max_length=20),
        ),
        migrations.AlterField(
            model_name='passengerdetail',
            name='meal_preference',
            field=models.CharField(choices=[('veg', 'Vegetarian'), ('nonveg', 'Non-Vegetarian'), ('none', 'No Meal')], max_length=10),
        ),
    ]
