# Generated by Django 4.2.16 on 2024-12-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0018_alter_booking_travel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(null=True),
        ),
    ]
